#!/usr/bin/env python3
#
# Copyright (C) 2018  Juerg Haefliger <juergh@gmail.com>
# Copyright (C) 2006  Anthony Liguori <anthony@codemonkey.ws>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.0 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

import argparse
import os
import signal
import sys

import gi
gi.require_version('Gtk', '3.0')

from gi.repository import Gtk
from gi.repository import GLib

from amt.power import AMTPower
from vnc.viewer import VNCViewer


# -----------------------------------------------------------------------------
# Main entry point

if __name__ == "__main__":

    desc = """
jvncviewer is a simple GTK VNC viewer.

The hostname and password (if necessary) need to be supplied via the
commandline or, alternatively, with environment variables VNC_HOST and
VNC_PASSWORD.
"""
    parser = argparse.ArgumentParser(description=desc, formatter_class=
                                     argparse.RawDescriptionHelpFormatter)
    parser.add_argument("host", metavar="host[:port]", nargs='?',
                        default=os.getenv("VNC_HOST", ""),
                        help="VNC host and (optional) port number. If not "
                        "specified, port defaults to '5900'.")
    parser.add_argument("password", nargs='?',
                        default=os.getenv("VNC_PASSWORD", ""),
                        help="VNC password.")
    args = parser.parse_args()

    if not args.host:
        parser.print_help()
        sys.exit(2)

    amt = AMTPower(args.host, "admin", args.password)
    vnc = VNCViewer(args.host, args.password, system=amt)

    vnc.connect()

    # Allow CTRL-C to quit the GTK main loop
    GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGINT, vnc.quit)
    Gtk.main()
